server:
  port: 8081
spring:
  data:
    redis:
      host: 172.16.1.104
      password: 1234
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.1.104:3306/aipub
    username: root
    password: 1234
  application:
    name: aipub
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: mt.aipub.entity
  configuration:
    map-underscore-to-camel-case: true

